# Site settings
title: Lima Post Campaign Report
baseurl: "/campaign-report/british-airways-lima"
url: "http://mp.secretescapes.com"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, bower.json, package.json, README.md, js/script.js, js/modernizr-custom.js]
